version: "3.8"

services:

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    env_file:
      - .env
    command: mongod --quiet --logpath /dev/null
  db:
    image: postgres:12
    container_name: antiprop_posgres
    env_file:
      - .env
    ports:
      - "5431:5432"

  redis:
    image: redis:alpine
    container_name: antiprop_redis
    ports:
      - "2342:2342"
    volumes:
      - ./storage/redis/data:/data
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" --save 20 1 --loglevel warning --port 2342

  web:
    build: .
    container_name: antiprop_Aiogrammwebhook
    command: bash -c 'python Testbot.py'
    volumes:
      - .:/code
    depends_on:
      - db
    network_mode: host
    ports:
      - "1443:1443"
    env_file:
      - .env
