channels = ["РИА Новости",[{("RIANEWS_media_1", "RIANEWS_caption_1"): ("RIANEWS_exposure_1", "RIANEWS_cap_exposure_1")},
     {("RIANEWS_media_2", "RIANEWS_caption_2"): ("RIANEWS_exposure_2", "RIANEWS_cap_exposure_2")},
     {("RIANEWS_media_3", "RIANEWS_caption_3"): ("RIANEWS_exposure_3", "RIANEWS_cap_exposure_3")},
     {("RIANEWS_media_4", "RIANEWS_caption_4"): ("RIANEWS_exposure_4", "RIANEWS_cap_exposure_4")},
     {("RIANEWS_media_5", "RIANEWS_caption_5"): ("RIANEWS_exposure_5", "RIANEWS_cap_exposure_5")}],

    "Russia Today",
    [{("RUSSIATODAY_media_1", "RUSSIATODAY_caption_1"): ("RUSSIATODAY_exposure_1", "RUSSIATODAY_cap_exposure_1")},
     {("RUSSIATODAY_media_2", "RUSSIATODAY_caption_2"): ("RUSSIATODAY_exposure_2", "RUSSIATODAY_cap_exposure_2")},
     {("RUSSIATODAY_media_3", "RUSSIATODAY_caption_3"): ("RUSSIATODAY_exposure_3", "RUSSIATODAY_cap_exposure_3")},
     {("RUSSIATODAY_media_4", "RUSSIATODAY_caption_4"): ("RUSSIATODAY_exposure_4", "RUSSIATODAY_cap_exposure_4")},
     {("RUSSIATODAY_media_5", "RUSSIATODAY_caption_5"): ("RUSSIATODAY_exposure_5", "RUSSIATODAY_cap_exposure_5")}],

    "Телеграм-каналы: Военный осведомитель / WarGonzo / Kotsnews",
    [{("TCHANEL_media_1", "TCHANEL_caption_1"): ("TCHANEL_exposure_1", "TCHANEL_cap_exposure_1")},
     {("TCHANEL_media_2", "TCHANEL_caption_2"): ("TCHANEL_exposure_2", "TCHANEL_cap_exposure_2")},
     {("TCHANEL_media_3", "TCHANEL_caption_3"): ("TCHANEL_exposure_3", "TCHANEL_cap_exposure_3")},
     {("TCHANEL_media_4", "TCHANEL_caption_4"): ("TCHANEL_exposure_4", "TCHANEL_cap_exposure_4")},
     {("TCHANEL_media_5", "TCHANEL_caption_5"): ("TCHANEL_exposure_5", "TCHANEL_cap_exposure_5")}],

    "Телеграм-канал: Война с фейками",
    [{("TCHANEL_WAR_media_1", "TCHANEL_WAR_caption_1"): ("TCHANEL_WAR_exposure_1", "TC_WAR_cap_exposure_1")},
     {("TCHANEL_WAR_media_2", "TCHANEL_WAR_caption_2"): ("TCHANEL_WAR_exposure_2", "TC_WAR_cap_exposure_2")},
     {("TCHANEL_WAR_media_3", "TCHANEL_WAR_caption_3"): ("TCHANEL_WAR_exposure_3", "TC_WAR_cap_exposure_3")},
     {("TCHANEL_WAR_media_4", "TCHANEL_WAR_caption_4"): ("TCHANEL_WAR_exposure_4", "TC_WAR_cap_exposure_4")},
     {("TCHANEL_WAR_media_5", "TCHANEL_WAR_caption_5"): ("TCHANEL_WAR_exposure_5", "TC_WAR_cap_exposure_5")}],

    "РБК", [{("RBK_media_1", "RBK_caption_1"): ("RBK_exposure_1", "RBK_cap_exposure_1")},
            {("RBK_media_2", "RBK_caption_2"): ("RBK_exposure_2", "RBK_cap_exposure_2")},
            {("RBK_media_3", "RBK_caption_3"): ("RBK_exposure_3", "RBK_cap_exposure_3")},
            {("RBK_media_4", "RBK_caption_4"): ("RBK_exposure_4", "RBK_cap_exposure_4")},
            {("RBK_media_5", "RBK_caption_5"): ("RBK_exposure_5", "RBK_cap_exposure_5")}],

    "ТАСС / Комсомольская правда / АиФ / Ведомости / Лента / Интерфакс",
     [{("TACC_media_1", "TACC_caption_1"): ("TACC_exposure_1", "TACC_cap_exposure_1")},
     {("TACC_media_2", "TACC_caption_2"): ("TACC_exposure_2", "TACC_cap_exposure_2")},
     {("TACC_media_3", "TACC_caption_3"): ("TACC_exposure_3", "TACC_cap_exposure_3")},
     {("TACC_media_4", "TACC_caption_4"): ("TACC_exposure_4", "TACC_cap_exposure_4")},
     {("TACC_media_5", "TACC_caption_5"): ("TACC_exposure_5", "TACC_cap_exposure_5")}],

    "Яндекс.Новости",
    [{("YANDEXNEWS_media_1", "YANDEXNEWS_caption_1"): ("YANDEXNEWS_exposure_1", "YNEWS_cap_exposure_1")},
     {("YANDEXNEWS_media_2", "YANDEXNEWS_caption_2"): ("YANDEXNEWS_exposure_2", "YNEWS_cap_exposure_2")},
     {("YANDEXNEWS_media_3", "YANDEXNEWS_caption_3"): ("YANDEXNEWS_exposure_3", "YNEWS_cap_exposure_3")},
     {("YANDEXNEWS_media_4", "YANDEXNEWS_caption_4"): ("YANDEXNEWS_exposure_4", "YNEWS_cap_exposure_4")},
     {("YANDEXNEWS_media_5", "YANDEXNEWS_caption_5"): ("YANDEXNEWS_exposure_5", "YNEWS_cap_exposure_5")}]]