from aiogram.dispatcher.fsm.state import StatesGroup, State


class StopWarState(StatesGroup):
    after_new_stat = State()
    stopwar_viva_la_resistance = State()
    stopwar_save_them = State()
    stopwar_big_responsibility = State()
    stopwar_time_is_marching = State()
    stopwar_ending = State()
    war_2 = State()
    stopwar_putin_already_lost = State()
    stopwar_putin_will_not_stop = State()
    stopwar_clever_bot = State()
    stopwar_war_eternal = State()
    stopwar_ofc = State()
    stopwar_will_it_stop = State()
    stopwar_borders_result = State()
    stopwar_ukraine_at_the_borders = State()
    stopwar_ukraine_will_not_stop = State()
    stopwar_nostradamus = State()
    stopwar_how_and_when = State()
    after_mobilisation = State()
    stopwar_lifesaver = State()
    stopwar_how_to_avoid = State()
    front_death = State()
    result = State()
    final = State()
    main = State()
    questions = State()
    must_watch = State()
    next_1 = State()
    war_1 = State()
    arg_1 = State()
    arg_2 = State()
    arg_3 = State()
