name: everyday db dump

on:
  workflow_dispatch:
  schedule:
    - cron: '17 12 * * *'

jobs:
  pg_dumping:
    runs-on: ubuntu-latest
    steps:
      - name: pg_dump
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_IP }}
          username: ec2-user
          key: ${{ secrets.SSHKEY }}
          connect_timeout: 10s
          script: |
            echo DUMPING PG
            mkdir -p Backups
            cd Backups
            sudo -S docker exec -t antiprop_posgres pg_dumpall -c -U postgres > ./DUMP.sql
