name: everyday db dump

on:
  workflow_dispatch:
  schedule:
    - cron: '17 12 * * *'

jobs:
  pg_dumping:
    runs-on: ubuntu-latest
    steps:
      - name: ALLDUMP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_IP }}
          username: ec2-user
          key: ${{ secrets.SSHKEY }}
          connect_timeout: 10s
          script: |
            echo Preparing
            sudo mkdir -p Backups/database
            cd Backups
            echo DUMPING PG
            sudo -S docker exec -t antiprop_posgres pg_dumpall -c -U postgres > ./PGDUMP.sql
            echo DUMPING MONGO
            sudo -S docker exec antipropagandabot-mongodb-1 mongodump -u mongoOTPOR -p mongoOTPOR --authenticationDatabase admin --db database -o /home
            sudo -S docker cp antipropagandabot-mongodb-1:/home/database /home/ec2-user/Backups
            echo Zipping
            zip -r BACKUP-$(date "+%b_%d_%Y").zip database PGDUMP.sql
            
      
        
