name: deploy to a server on push

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:

      - uses: appleboy/ssh-action@master
        with:
          host: ec2-16-170-206-95.eu-north-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSHKEY }}
      
          script:
            sudo service docker start
            cd antipropagandabot\
            git pull
            sleep 5
            docker compose build
            docker compose up
