name: deploy to a server on push

on:
  push:
    branches: 
      - '!new_dev'
      - '!master'
    tags:
      - 1.*

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:

      - uses: appleboy/ssh-action@master
        with:
          host: 16.170.208.192
          username: ${{ secrets.AMAZON_USERNAME }}
          key: ${{ secrets.SSHKEY }}
      
          script: |
            sudo su
            cd /root/antipropagandabot/
            git pull
            sleep 5
            docker docker restart 92dc5d4cc46f
