name: deploy to a server on push

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER }}
          username: ${{ secrets.AMAZON_USERNAME }}
          key: ${{ secrets.SSHKEY }}
      
          script: |
            sudo service docker start
            cd antipropagandabot/
            git pull
            sleep 5
            docker compose build
            docker compose up
