name: deploy to a server on push

on:
  push:
    branches: 
      - '!new_dev'
      - '!master'
    tags:
      - 1.*

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipeline 1
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.TEST_SERVER }}
          user: ${{ secrets.AMAZON_USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          connect_timeout: 10s
          script: |
            ls -la
            echo WELCOME
            sudo su -
            ls -la
            cd antipropagandabot
            git pull

