name: Stage Deploy

on:
  workflow_run:
    workflows: [ Test Pipeline ]
    types:
      - completed

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: ssh pipeline 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_IP }}
          username: ec2-user
          key: ${{ secrets.SSHKEY }}
          connect_timeout: 10s
          script: |
            echo WELCOME
            cd antipropagandabot
            sudo -S git pull
            sudo -S docker restart antiprop_Aiogrammwebhook

