name: deploy to a server on push

on:
  push:
    branches: 
      - '!new_dev'
      - '!master'
    tags:
      - 1.*

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_IP }}
          username: ${{ secrets.AMAZON_USERNAME }}
          key: ${{ secrets.SSHKEY }}
      
          script: |
            ls
            sudo su -
            ls
            cd antipropagandabot
            ls
            git pull
            sleep 5
            docker restart 92dc5d4cc46f
