name: deploy to a server on push

on:
  push:
    branches: 
      - '!new_dev'
      - '!master'
    tags:
      - 1.*

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipeline 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_IP }}
          username: ec2-user
          key: ${{ secrets.SSHKEY }}
          connect_timeout: 10s
          script: |
            ls -la
            echo WELCOME
            sudo su
            cd /root
            ls -la
            cd antipropagandabot
            git pull

