name: Test Pipiline

on:
  workflow_dispatch:
  push:
    branches:
      - test


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Making .env'
        run: |
          touch .env
          cat .env.example >> .env
          echo \n >> .env
          echo BOT_TOKEN = 5483385115:AAG3VIZEBtFlNnHiSzOhL4nf9ZluT-PNh34 >> .env
          echo TEST_CHANNEL_ID = -1001270576526 >> .env
          echo TEST_USER_ID = 5429649862 >> .env
          cat .env
      - name: 'Building containers'
        run: docker compose -f CI/DocTesting.yml build
      - name: 'Testing'
        run: docker compose -f CI/DocTesting.yml up --abort-on-container-exit
      - name: 'Report upload'
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: |
            pytest_html_report.html
            flake8_report