name: Test Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Making .env'
        run: |
          touch .env
          ${{ secrets.ENV_TEST }}
      - name: 'Building containers'
        run: docker compose -f CI/DocTesting.yml build
      - name: 'Testing'
        id: testing
        run: docker compose -f CI/DocTesting.yml up --abort-on-container-exit
      - name: 'Report upload'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: |
            pytest_html_report.html
            flake8_report
      - name: get file changes
        run: |
          mkdir artifacts
          echo $(git log --pretty=format:%s, ${{ github.event.before }}...${{ github.event.after }}) > artifacts/commi
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: commi
          path: artifacts/commi
