version: "3.8"

services:

  web:
    build: .
    container_name: flasktest
    command: bash -c 'python main.py'
    volumes:
      - .:/codefl
    ports:
      - "5000:5000"
    depends_on:
      - db


  db:
    image: postgres:12
    container_name: flasktest_posgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

